spring:
  application:
    name: learn-ktorm
  datasource:
    url: jdbc:h2:mem:080174c0-d6c2-4c43-b2cb-75e2c6e559ee;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;MODE=MYSQL
    username: sa
  sql:
    init:
      platform: mysql
  h2:
    console:
      enabled: true
decorator:
  datasource:
    p6spy:
      logging: slf4j
      log-format: "#%(currentTime) | %(executionTime)ms | %(category) | %(sqlSingleLine)"
